In [2]:
!pip3 install pandas

Requirement already satisfied: pandas in c:\users\marizze julliane\onedrive\desktop\mark\dashiq\venv\lib\site-packages (3.0.2)
Requirement already satisfied: numpy>=1.26.0 in c:\users\marizze julliane\onedrive\desktop\mark\dashiq\venv\lib\site-packages (from pandas) (2.4.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\marizze julliane\onedrive\desktop\mark\dashiq\venv\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\marizze julliane\onedrive\desktop\mark\dashiq\venv\lib\site-packages (from pandas) (2026.1)
Requirement already satisfied: six>=1.5 in c:\users\marizze julliane\onedrive\desktop\mark\dashiq\venv\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 25.1.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [17]:
import pandas as pd
from pathlib import Path

In [ ]:
# Get the current notebook directory
notebook_dir = Path.cwd()  # This points to the folder where the notebook is running

# Construct the correct path to your CSV
data_path = notebook_dir / "../data/raw/sales_records.csv"

# Resolve full absolute path (optional, just for debugging)
data_path = data_path.resolve()
print("Reading from:", data_path)

# Load dataset
df = pd.read_csv(data_path)

# Show first 5 rows
df.head()

Reading from: C:\Users\Marizze Julliane\OneDrive\Desktop\Mark\DashIQ\data\raw\sales_records.csv

,Region,Country,Item Type,Sales Channel,Order Priority,Order Date,Order ID,Ship Date,Units Sold,Unit Price,Unit Cost,Total Revenue,Total Cost,Total Profit
0,Sub-Saharan Africa,South Africa,Fruits,Offline,M,7/27/2012,443368995,7/28/2012,1593,9.33,6.92,14862.69,11023.56,3839.13
1,Middle East and North Africa,Morocco,Clothes,Online,M,9/14/2013,667593514,10/19/2013,4611,109.28,35.84,503890.08,165258.24,338631.84
2,Australia and Oceania,Papua New Guinea,Meat,Offline,M,5/15/2015,940995585,6/4/2015,360,421.89,364.69,151880.40,131288.40,20592.00
3,Sub-Saharan Africa,Djibouti,Clothes,Offline,H,5/17/2017,880811536,7/2/2017,562,109.28,35.84,61415.36,20142.08,41273.28
4,Europe,Slovakia,Beverages,Offline,L,10/26/2016,174590194,12/4/2016,3973,47.45,31.79,188518.85,126301.67,62217.18

In [37]:
df.shape

(1000000, 14)

In [ ]:
df.columns

In [ ]:
df.info

In [ ]:
#data types of each column as expected, but if we want to do date-based analysis, we need to change the date columns to datetime format
df.dtypes

Region                       str
Country                      str
Item Type                    str
Sales Channel                str
Order Priority               str
Order Date        datetime64[us]
Order ID                   int64
Ship Date         datetime64[us]
Units Sold                 int64
Unit Price               float64
Unit Cost                float64
Total Revenue            float64
Total Cost               float64
Total Profit             float64
dtype: object

In [ ]:
#only needed to change the date columns to datetime format for future analysis
df["Order Date"] = pd.to_datetime(df["Order Date"])
df["Ship Date"] = pd.to_datetime(df["Ship Date"])

df.dtypes

Region                       str
Country                      str
Item Type                    str
Sales Channel                str
Order Priority               str
Order Date        datetime64[us]
Order ID                   int64
Ship Date         datetime64[us]
Units Sold                 int64
Unit Price               float64
Unit Cost                float64
Total Revenue            float64
Total Cost               float64
Total Profit             float64
dtype: object

In [44]:
#Checking for Order Date range
print("Order Date range:", df["Order Date"].min(), "to", df["Order Date"].max())
print("Ship Date range:", df["Ship Date"].min(), "to", df["Ship Date"].max())

Order Date range: 2010-01-01 00:00:00 to 2017-07-29 00:00:00
Ship Date range: 2010-01-01 00:00:00 to 2017-09-17 00:00:00

In [46]:
#Checking missing values
print("Missing values per column:")
print(df.isnull().sum())

Missing values per column:
Region            0
Country           0
Item Type         0
Sales Channel     0
Order Priority    0
Order Date        0
Order ID          0
Ship Date         0
Units Sold        0
Unit Price        0
Unit Cost         0
Total Revenue     0
Total Cost        0
Total Profit      0
dtype: int64

In [49]:
#CHecking for duplicates
print("Number of duplicate rows:", df.duplicated().sum())

Number of duplicate rows: 50009

In [50]:
#summary of statistics for numeric columns
df.describe()

,Order Date,Order ID,Ship Date,Units Sold,Unit Price,Unit Cost,Total Revenue,Total Cost,Total Profit
count,1000000,1.000000e+06,1000000,1000000.000000,1000000.000000,1000000.000000,1.000000e+06,1.000000e+06,1.000000e+06
mean,2013-10-14 22:41:24.979199,5.493520e+08,2013-11-08 23:03:51.004801,4998.867302,266.025488,187.522978,1.329563e+06,9.372671e+05,3.922956e+05
min,2010-01-01 00:00:00,1.000012e+08,2010-01-01 00:00:00,1.000000,9.330000,6.920000,9.330000e+00,6.920000e+00,2.410000e+00
25%,2011-11-22 00:00:00,3.239629e+08,2011-12-17 00:00:00,2502.000000,81.730000,35.840000,2.778672e+05,1.617289e+05,9.510480e+04
50%,2013-10-15 00:00:00,5.486524e+08,2013-11-09 00:00:00,4998.000000,154.060000,97.440000,7.844445e+05,4.667818e+05,2.810549e+05
75%,2015-09-08 00:00:00,7.745981e+08,2015-10-02 00:00:00,7496.000000,421.890000,263.330000,1.822444e+06,1.196327e+06,5.653076e+05
max,2017-07-29 00:00:00,9.999999e+08,2017-09-17 00:00:00,10000.000000,668.270000,524.960000,6.682700e+06,5.249600e+06,1.738700e+06
std,NaN,2.599397e+08,NaN,2885.334142,216.987966,175.650798,1.468527e+06,1.148954e+06,3.788199e+05