In [1]:
import pandas as pd
from pathlib import Path

In [ ]:
notebook_dir = Path.cwd() 

data_path = notebook_dir / "../data/raw/sales_records.csv"

data_path = data_path.resolve()
print("Reading from:", data_path)

df = pd.read_csv(data_path)

df.head()

Reading from: C:\Users\Marizze Julliane\OneDrive\Desktop\Mark\DashIQ\data\raw\sales_records.csv

,Region,Country,Item Type,Sales Channel,Order Priority,Order Date,Order ID,Ship Date,Units Sold,Unit Price,Unit Cost,Total Revenue,Total Cost,Total Profit
0,Sub-Saharan Africa,South Africa,Fruits,Offline,M,7/27/2012,443368995,7/28/2012,1593,9.33,6.92,14862.69,11023.56,3839.13
1,Middle East and North Africa,Morocco,Clothes,Online,M,9/14/2013,667593514,10/19/2013,4611,109.28,35.84,503890.08,165258.24,338631.84
2,Australia and Oceania,Papua New Guinea,Meat,Offline,M,5/15/2015,940995585,6/4/2015,360,421.89,364.69,151880.40,131288.40,20592.00
3,Sub-Saharan Africa,Djibouti,Clothes,Offline,H,5/17/2017,880811536,7/2/2017,562,109.28,35.84,61415.36,20142.08,41273.28
4,Europe,Slovakia,Beverages,Offline,L,10/26/2016,174590194,12/4/2016,3973,47.45,31.79,188518.85,126301.67,62217.18

In [ ]:

#Checking missing values per column
print("Missing values per column:")
print(df.isnull().sum())
#or
missing_values = df.isnull().sum()
missing_values

In [8]:
# Total missing values in the dataset
df.isnull().sum().sum()

np.int64(0)

In [10]:
# Missing value percentage
missing_percent = (df.isnull().sum() / len(df)) * 100
missing_percent[missing_percent > 0]

Series([], dtype: float64)

In [11]:
# Create missing value summary report
missing_report = pd.DataFrame({
    "Missing Count": df.isnull().sum(),
    "Missing Percentage": (df.isnull().sum() / len(df)) * 100
})

# Show only columns with missing values
missing_report = missing_report[missing_report["Missing Count"] > 0]

missing_report

Empty DataFrame
Columns: [Missing Count, Missing Percentage]
Index: []