In [4]:
import pandas as pd
from pathlib import Path

In [ ]:
notebook_dir = Path.cwd()

data_path = notebook_dir / "../data/raw/sales_records.csv"

data_path = data_path.resolve()
print("Reading from:", data_path)

df = pd.read_csv(data_path)

df.head()

Reading from: C:\Users\Marizze Julliane\OneDrive\Desktop\Mark\DashIQ\data\raw\sales_records.csv

,Region,Country,Item Type,Sales Channel,Order Priority,Order Date,Order ID,Ship Date,Units Sold,Unit Price,Unit Cost,Total Revenue,Total Cost,Total Profit
0,Sub-Saharan Africa,South Africa,Fruits,Offline,M,7/27/2012,443368995,7/28/2012,1593,9.33,6.92,14862.69,11023.56,3839.13
1,Middle East and North Africa,Morocco,Clothes,Online,M,9/14/2013,667593514,10/19/2013,4611,109.28,35.84,503890.08,165258.24,338631.84
2,Australia and Oceania,Papua New Guinea,Meat,Offline,M,5/15/2015,940995585,6/4/2015,360,421.89,364.69,151880.40,131288.40,20592.00
3,Sub-Saharan Africa,Djibouti,Clothes,Offline,H,5/17/2017,880811536,7/2/2017,562,109.28,35.84,61415.36,20142.08,41273.28
4,Europe,Slovakia,Beverages,Offline,L,10/26/2016,174590194,12/4/2016,3973,47.45,31.79,188518.85,126301.67,62217.18

In [21]:
# Count exact duplicate rows
duplicate_count = df.duplicated().sum()
duplicate_count

np.int64(0)

In [7]:
# Show duplicate rows
duplicate_rows = df[df.duplicated()]
duplicate_rows.head()

,Region,Country,Item Type,Sales Channel,Order Priority,Order Date,Order ID,Ship Date,Units Sold,Unit Price,Unit Cost,Total Revenue,Total Cost,Total Profit
747904,Central America and the Caribbean,Trinidad and Tobago,Personal Care,Offline,M,4/20/2015,370419776,5/4/2015,4298,81.73,56.67,351275.54,243567.66,107707.88
747907,Sub-Saharan Africa,Djibouti,Clothes,Offline,H,5/27/2010,667237317,6/27/2010,9204,109.28,35.84,1005813.12,329871.36,675941.76
747908,Sub-Saharan Africa,Tanzania,Cosmetics,Online,L,9/16/2016,214140975,10/19/2016,7928,437.20,263.33,3466121.60,2087680.24,1378441.36
747909,Australia and Oceania,Australia,Household,Offline,L,1/12/2011,222868669,2/23/2011,647,668.27,502.54,432370.69,325143.38,107227.31
747913,Europe,Denmark,Meat,Offline,C,9/24/2012,244183862,10/28/2012,8286,421.89,364.69,3495780.54,3021821.34,473959.20

In [19]:
# Count duplicate Order IDs
duplicate_order_ids = df["Order ID"].duplicated().sum()
duplicate_order_ids

np.int64(100000)

In [20]:
# Show rows with repeated Order IDs (For Removal)
repeated_orders = df[df["Order ID"].duplicated(keep=False)].sort_values("Order ID")
repeated_orders.head(10)

,Region,Country,Item Type,Sales Channel,Order Priority,Order Date,Order ID,Ship Date,Units Sold,Unit Price,Unit Cost,Total Revenue,Total Cost,Total Profit,is_duplicate
782778,Europe,Ukraine,Cosmetics,Offline,H,12/1/2014,100016200,12/28/2014,5871,437.20,263.33,2566801.20,1546010.43,1020790.77,True
434874,Europe,Ukraine,Cosmetics,Offline,H,12/1/2014,100016200,12/28/2014,5871,437.20,263.33,2566801.20,1546010.43,1020790.77,False
423998,Asia,Malaysia,Household,Offline,L,1/17/2016,100017917,1/27/2016,6379,668.27,502.54,4262894.33,3205702.66,1057191.67,False
771902,Asia,Malaysia,Household,Offline,L,1/18/2016,100017917,1/28/2016,6379,668.27,502.54,4262894.33,3205702.66,1057191.67,False
432733,Sub-Saharan Africa,Angola,Vegetables,Offline,L,10/24/2010,100024354,12/9/2010,8284,154.06,90.93,1276233.04,753264.12,522968.92,False
780637,Sub-Saharan Africa,Angola,Vegetables,Offline,L,10/24/2010,100024354,12/9/2010,8284,154.06,90.93,1276233.04,753264.12,522968.92,True
474000,Europe,Serbia,Meat,Online,L,9/7/2012,100053107,9/16/2012,6793,421.89,364.69,2865898.77,2477339.17,388559.60,False
821904,Europe,Serbia,Meat,Online,L,9/7/2012,100053107,9/16/2012,6793,421.89,364.69,2865898.77,2477339.17,388559.60,True
759386,Sub-Saharan Africa,Guinea-Bissau,Vegetables,Online,M,8/22/2014,100084865,10/5/2014,6190,154.06,90.93,953631.40,562856.70,390774.70,True
411482,Sub-Saharan Africa,Guinea-Bissau,Vegetables,Online,M,8/22/2014,100084865,10/5/2014,6190,154.06,90.93,953631.40,562856.70,390774.70,False

In [18]:
# Create a flag for duplicate
# Mark exact duplicate rows
df["is_duplicate"] = df.duplicated()

# Count flagged duplicates
df["is_duplicate"].value_counts()

is_duplicate
False    949991
True      50009
Name: count, dtype: int64

In [14]:
# Marked for removal
rows_marked_for_removal = df[df["is_duplicate"] == True]
rows_marked_for_removal.head()

Empty DataFrame
Columns: [Region, Country, Item Type, Sales Channel, Order Priority, Order Date, Order ID, Ship Date, Units Sold, Unit Price, Unit Cost, Total Revenue, Total Cost, Total Profit, is_duplicate]
Index: []

In [17]:
# Saving duplicate rows for audit trail
output_path = data_path.parent / "duplicate_rows_review.csv"
rows_marked_for_removal.to_csv(output_path, index=False)