In [1]:
import pandas as pd
from pathlib import Path

In [2]:
# Load clean Data
notebook_dir = Path.cwd()  
data_path = notebook_dir / "../data/cleaned/sales_records_clean.csv"

data_path = data_path.resolve()
print("Reading from:", data_path)

df = pd.read_csv(data_path)


df["Order Date"] = pd.to_datetime(df["Order Date"])

df.head()

Reading from: C:\Users\Marizze Julliane\OneDrive\Desktop\Mark\DashIQ\data\cleaned\sales_records_clean.csv

,Region,Country,Item Type,Sales Channel,Order Priority,Order Date,Order ID,Ship Date,Units Sold,Unit Price,Unit Cost,Total Revenue,Total Cost,Total Profit
0,Sub-Saharan Africa,South Africa,Fruits,Offline,M,2012-07-27,443368995,2012-07-28,1593,9.33,6.92,14862.69,11023.56,3839.13
1,Middle East And North Africa,Morocco,Clothes,Online,M,2013-09-14,667593514,2013-10-19,4611,109.28,35.84,503890.08,165258.24,338631.84
2,Australia And Oceania,Papua New Guinea,Meat,Offline,M,2015-05-15,940995585,2015-06-04,360,421.89,364.69,151880.40,131288.40,20592.00
3,Sub-Saharan Africa,Djibouti,Clothes,Offline,H,2017-05-17,880811536,2017-07-02,562,109.28,35.84,61415.36,20142.08,41273.28
4,Europe,Slovakia,Beverages,Offline,L,2016-10-26,174590194,2016-12-04,3973,47.45,31.79,188518.85,126301.67,62217.18

In [5]:
df["Year"] = df["Order Date"].dt.year

In [6]:
df["Month"] = df["Order Date"].dt.month

In [8]:
df["Month"] = df["Order Date"].dt.month

In [9]:
# Avoiding division error
df["Profit Margin"] = df["Total Profit"] / df["Total Revenue"]
df["Profit Margin"] = df["Profit Margin"].fillna(0)

In [11]:
df["Profit Margin (%)"] = df["Profit Margin"] * 100

In [12]:
def discount_bucket(margin):
    if margin < 0.1:
        return "High Discount"
    elif margin < 0.3:
        return "Medium Discount"
    else:
        return "Low Discount"

df["Discount Bucket"] = df["Profit Margin"].apply(discount_bucket)

In [14]:
df.head()

,Region,Country,Item Type,Sales Channel,Order Priority,Order Date,Order ID,Ship Date,Units Sold,Unit Price,Unit Cost,Total Revenue,Total Cost,Total Profit,Month,Year,Profit Margin,Profit Margin (%),Discount Bucket
0,Sub-Saharan Africa,South Africa,Fruits,Offline,M,2012-07-27,443368995,2012-07-28,1593,9.33,6.92,14862.69,11023.56,3839.13,7,2012,0.258307,25.830654,Medium Discount
1,Middle East And North Africa,Morocco,Clothes,Online,M,2013-09-14,667593514,2013-10-19,4611,109.28,35.84,503890.08,165258.24,338631.84,9,2013,0.672035,67.203514,Low Discount
2,Australia And Oceania,Papua New Guinea,Meat,Offline,M,2015-05-15,940995585,2015-06-04,360,421.89,364.69,151880.40,131288.40,20592.00,5,2015,0.135580,13.558036,Medium Discount
3,Sub-Saharan Africa,Djibouti,Clothes,Offline,H,2017-05-17,880811536,2017-07-02,562,109.28,35.84,61415.36,20142.08,41273.28,5,2017,0.672035,67.203514,Low Discount
4,Europe,Slovakia,Beverages,Offline,L,2016-10-26,174590194,2016-12-04,3973,47.45,31.79,188518.85,126301.67,62217.18,10,2016,0.330032,33.003161,Low Discount

In [16]:
df.columns

Index(['Region', 'Country', 'Item Type', 'Sales Channel', 'Order Priority',
       'Order Date', 'Order ID', 'Ship Date', 'Units Sold', 'Unit Price',
       'Unit Cost', 'Total Revenue', 'Total Cost', 'Total Profit', 'Month',
       'Year', 'Profit Margin', 'Profit Margin (%)', 'Discount Bucket'],
      dtype='str')

In [17]:
df.to_csv("../data/cleaned/sales_records_enhanced.csv", index=False)